--- 
  - name: install uWSGI packages
    apt:
      pkg:
      - uwsgi
      - uwsgi-plugin-python3

  - name: Start uWSGI
    service: 
      name: uwsgi 
      state: started 
    
  - name: copy uwsgi config file
    copy:
      src: /home/rashad/ica0002/roles/uwsgi/files/agama.ini
      dest: /etc/uwsgi/apps-enabled/agama.ini
    become: yes
    notify: restart uwsgi 
