--- 
- name: install uWSGI packages
  apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3
    - python3-pymysql

- name: Start uWSGI
  service: 
    name: uwsgi 
    state: started 
    
- name: copy uwsgi config file
  template:
    src: /home/rashad/ica0002/roles/uwsgi/templates/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  become: yes
  notify: restart uwsgi 
