---
- name: Bind Install
  apt:
    name: bind9
    state: present

- name: Ensure bind9 is running
  service:
    name: bind9
    state: started
    enabled: yes

#Unsure of what to copy here. 

- name: Set DNS Server to host1
  lineinfile:
   regexp: '8.8.8.8'
   insertafter: '^#'
   line: nameserver 8.8.8.8
   path: /etc/resolv.conf

- name: Install bind
  apt:
    pkg: bind9
    state: present

- name: Set hostname
  hostname:
    name: "{{ hostname }}.{{ domain }}"

- name: Set hostname fact
  set_fact:
    ansible_fqdn: "{{ hostname}}.{{domain }}"

# - name: Copy named conf file
#   template:
#     src: named.conf.j2
#     dest: /etc/named.conf
#     owner: root
#     group: bind
#     mode: 0660
#   notify: restart bind9

- name: Make "custombind9" directory
  file:
    path: /etc/custombind
    state: directory
    owner: root
    group: bind
    mode: 0750

- name: Copy named conf local file
  template:
    src: named.conf.local.j2
    dest: /etc/custombind/named.conf.local
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9

- name: Make zones Directory
  file:
    path: /etc/custombind/zones
    state: directory
    owner: root
    group: bind
    mode: 0750

- name: Copy forward file
  template:
    src: db.forward.j2
    dest: /etc/custombind/zones/db.forward
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9

- name: Copy reverse file
  template:
    src: db.reverse.j2
    dest: /etc/custombind/zones/db.reverse
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9

- name: check if firewalld is running
  command: systemctl is-active firewalld
  register: firewalld_result
  changed_when: False
  ignore_errors: True

- name: Open firewall port
  firewalld:
   service: dns
   permanent: true
   state: enabled
   immediate: yes
  when: firewalld_result.stdout == "active"

- name: Copy resolv.conf file
  template:
    src: resolve.conf.j2
    dest: /etc/custombind/resolve.conf
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9