--- 
- name: user make
  user:
    name: roman
    name: juri

- name: Roman SSH key  
  authorized_key:
    user: roman
    state: present
    key: https://github.com/romankuchin.keys

- name: Juri SSH key
  authorized_key:
    user: juri
    state: present
    key: https://github.com/hudolejev.keys
      

     
  
     

