---
- name: Install Bind9
  apt:
    name: bind9
    update_cache: yes

- name: Ensure bind9 is running
  service:
    name: bind9
    state: started
    
- name : Update named.config file
  template:
    src: roles/bind/templates/named.conf.options
    dest: /etc/bind/named.conf.options
  notify: restart bind9
